### ISSUE TITLE
install failed 

### ISSUE THREAD

**Issue by Mohamed3bdelwahab** [AkariOficial/termux-packages#1]
hi bro I'm  having issue to run frida with python 3.11
and see your comment and try to install python  but get failed to install  .

![Screenshot_2022-11-18-02-22-19-660_com termux](https://user-images.githubusercontent.com/24799844/202588177-94152339-7733-4009-bd8f-63dab8b22824.jpg)
![Screenshot_2022-11-18-02-22-17-414_com termux](https://user-images.githubusercontent.com/24799844/202588181-aaf9d003-0081-4200-b521-f656e108e33c.jpg)
![Screenshot_2022-11-18-02-22-14-718_com termux](https://user-images.githubusercontent.com/24799844/202588186-e7669f5d-975d-4d3c-abca-c05171ae9865.jpg)
![Screenshot_2022-11-18-02-22-11-973_com termux](https://user-images.githubusercontent.com/24799844/202588189-f0802672-9f95-466c-a558-0a6ad6d4c2f2.jpg)

**Comment by Mohamed3bdelwahab** [comment]
I'm  aarch64
  too

**Comment by whyakari** [comment]
@a-gamer 

did you install the other dependencies?
with ` git clone https://github.com/AkariOficial/termux-packages; cd termux-packages; cd python3.10.8; dpkg -i *.deb` ?

**Comment by Mohamed3bdelwahab** [comment]
It's workink fine after install python 3.11  install this  version without uninstall and working

**Comment by whyakari** [comment]
> It's workink fine after install python 3.11 install this version without uninstall and working

ok, thanks a lot for letting me know. I believe now frida-tools is working in python 3.11. correct?

**Comment by Mohamed3bdelwahab** [comment]
no   i have install python 3.11 and install pkg install frida-python frida 
after that installed  your pkg python3.10.8
pio install frida-tools==10.8  
 so your pkg it's  working fine  without any error .

**Comment by whyakari** [comment]
> no i have install python 3.11 and install pkg install frida-python frida after that installed your pkg python3.10.8 pio install frida-tools==10.8 so your pkg it's working fine without any error .

ooh glad it worked for you! Thanks for sharing, I'll add it to the READMD.md
